version: '3'
services:
  database:
    image: postgres:11-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auction_marketplace
  adminer:
    image: adminer:latest
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: root
